/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cli_calculator;

import java.text.NumberFormat;
import java.util.Scanner;

import error.*;
import manager.StaticVariableManager;

public class App {
    private static Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println(StaticVariableManager.scriptString);

        while (true) {
            try {
                if (printMenu()) {
                    break;
                }
            } catch (ErrorHandler e) {
                e.PrintError();
            }
        }
    }

    // 메뉴 기능
    private static boolean printMenu() throws ErrorHandler {
        System.out.print(StaticVariableManager.menuString + "> ");
        String expression = scanner.nextLine();

        switch (expression) {
            case "1":
                System.out.println(StaticVariableManager.scriptString);
                break;
            case "2":
                generateCalculator();
                break;
            case "3":
                System.out.println(StaticVariableManager.exitString);
                return true;
            default:
                throw new ErrorHandler(ErrorType.COMMAND_ERROR);
        }
        return false;
    }

    // 계산 기능
    private static void generateCalculator() {
        Calculator calculator = new Calculator();

        while (true) {
            System.out.print(StaticVariableManager.calculatorString);
            String expression = scanner.nextLine();

            if (expression.equals("q")) {
                break;
            }

            try {
                double result = calculator.calculate(expression);

                if (Double.isNaN(result)) {
                    System.out.println("SUCCESS");
                } else {
                    if (result == (int) result) {
                        System.out.println((int) result);
                    } else {
                        NumberFormat numberFormat = NumberFormat.getInstance();
                        numberFormat.setMaximumFractionDigits(6);
                        numberFormat.setGroupingUsed(false);
                        System.out.println(numberFormat.format(result));
                    }
                }

            } catch (ErrorHandler e) {
                e.PrintError();
            }
        }
    }
}
